### ISSUE TITLE
The declared package does not match the expected package error

### ISSUE THREAD

**Issue by IdsAndriesse** [rug-oop/2019_assignments#4] opened 2019-04-23 19:44 UTC
When running the mvn integration-test command I receive the error stated in the title. This was resolved by adding

package nl.rug.oop.helloWorld;

However, now when I compile and run with any of the commands in 6.8, I get the following error:

java.lang.ClassNotFoundExeption : Main

Also something peculiar: the classes do now appear in /target/classes/nl/oop/helloWorld instead of target/classes. I think this is the problem when running. My question is, how to solve this problem? And does the adding of the package matter when I hand in the assignment?

**Comment by CRefice** [comment] 2019-04-24 19:17
This is a duplicate of the other issue.

**Comment by nmozilla** [comment] 2019-04-24 19:39
I think by now you probably found the solution. But, it could be something related to the dependencies of the packages. If you still have this issue, please let me know.

**Closed** 2019-04-26 10:46 UTC
